logging:
  level:
    .: INFO
    org.springframework: INFO
    de.codecentric.spring.boot.chaos: DEBUG

---

spring:
  profiles: chaos-monkey
  main:
    banner-mode: "off"

# Spring Cloud Chaos Configuration
chaos.monkey.enabled: true
management.endpoint.chaosmonkey.enabled: true
management.endpoint.chaosmonkeyjmx.enabled: true
management.endpoints.web.exposure.include: "*"

chaos.monkey.assaults.level: 3
chaos.monkey.assaults.latencyActive: true
chaos.monkey.assaults.latencyRangeStart: 3000
chaos.monkey.assaults.latencyRangeEnd: 15000
chaos.monkey.assaults.exceptionsActive: true
chaos.monkey.assaults.killApplicationActive: true

chaos.monkey.watcher.controller: false
chaos.monkey.watcher.restController: true
chaos.monkey.watcher.service: false
chaos.monkey.watcher.repository: false
chaos.monkey.watcher.component: false


